export const PROVIDER_METADATA_TIMEOUT_MS = 60_000;
export const OPENAI_METADATA_TIMEOUT_MS = PROVIDER_METADATA_TIMEOUT_MS;
export const DASHBOARD_USAGE_REQUEST_TIMEOUT_MS = 90_000;
export const DAEMON_CONTROL_IDLE_TIMEOUT_SECONDS = 120;
export const MODEL_STREAM_IDLE_TIMEOUT_MS = 10 * 60_000;
export const MODEL_TOTAL_TIMEOUT_MS = 30 * 60_000;
export const NATIVE_COMPACTION_TIMEOUT_MS = 10 * 60_000;
